namespaces:
  infra: infra
  app: app

postgres:
  image: postgres:15-alpine
  env:
    POSTGRES_DB: kubecoin
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
  volume:
    name: postgres-storage
    size: 1Gi
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"

kafka:
  enabled: false
  image: obsidiandynamics/kafka:latest
  volume:
    name: kafka-storage
    size: 2Gi
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"

backend:
  image:
    repository: docker.io/privatergistry/kubecoin-backend
    tag: latest
  env:
    DB_HOST: postgres-headless.infra.svc.cluster.local
    DB_NAME: kubecoin
    DB_USER: postgres
    DB_PASSWORD: password
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"

frontend:
  image:
    repository: docker.io/privatergistry/kubecoin-frontend
    tag: latest
  env:
    BACKEND_URL: http://backend-service.app.svc.cluster.local:5000
  resources:
    limits:
      cpu: "250m"
      memory: "256Mi"
