{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.namespaces.infra }}
spec:
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: {{ .Values.namespaces.infra }}
spec:
  serviceName: kafka
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: {{ .Values.kafka.image }}
          ports:
            - containerPort: 9092
          resources:
            limits:
              cpu: {{ .Values.kafka.resources.limits.cpu | quote }}
              memory: {{ .Values.kafka.resources.limits.memory | quote }}
          volumeMounts:
            - name: {{ .Values.kafka.volume.name }}
              mountPath: /bitnami/kafka
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.kafka.volume.name }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.kafka.volume.size }}
{{- end }}
