apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  DB_HOST: postgres-headless.infra.svc.cluster.local
  DB_NAME: kubecoin
  BACKEND_URL: http://backend-service.app.svc.cluster.local:5000
  KAFKA_BOOTSTRAP_SERVERS: kafka.infra.svc.cluster.local:9092
