apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:15-alpine
          command: ['sh', '-c', 'until pg_isready -h $DB_HOST -U $DB_USER -d $DB_NAME; do echo waiting for database; sleep 2; done;']
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
      containers:
        - name: backend
          image: docker.io/your-dockerhub-user/kubecoin-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
